kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demooci-fss-0cd12f6c
spec:
  storageClassName: "oci-fss"
  selector:
    matchLabels:
      oci-availability-domain: "PHX-AD-2"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
